Name=Mypal (Legacy)
Id=mypal-legacy
Icon=https://img.biblprog.org.ua/programsimages/mypal/mypal_icon.png
Version=29.3.0
Alversion=0
Publisher=Feodor2
Developer=Feodor2
InstallType=DownloadAndRun
Installer=https://www.mypal-browser.org/release/mypal-29.3.0.win32.installer.exe
